FROM golang:1.25.2-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -ldflags="-w -s" -o main ./cmd/spl-notification/main.go

FROM golang:1.25.2-alpine
WORKDIR /app
COPY --from=build /app/main .
COPY --from=build /app/.env .

# Turso Migrations
COPY --from=build /app/migrations/*.sql /app/migrations/

# Google Credentials
COPY --from=build /app/google-credentials.json .
EXPOSE 8000

CMD ["./main"]